### ISSUE TITLE
Possibility to share custom media name and value with JS

### ISSUE THREAD

**Issue by aFarkas** [postcss/postcss-custom-media#12]
It would be nice to write all custom media names and their values as `content` or `font-family` to the html or head element. 

This would be helpfull to create a polyfill, monkey patch `matchMedia` and/or improve [responsive images](https://github.com/aFarkas/lazysizes/tree/master/plugins/custommedia):

``` html
<picture>
    <source
        srcset="http://placehold.it/500x600/11e87f/fff"
        media="--small" />
    <source
        srcset="http://placehold.it/700x300"
        media="--medium" />
    <source
        srcset="http://placehold.it/1400x600/e8117f/fff"
        media="--large" />
    <img
        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
        alt="image with artdirection" />
</picture>
```

**Comment by MoOx** [comment]
Currently, you have multiples possibilities:
- you can use [preserve option](https://github.com/postcss/postcss-custom-media#preserve) to keep the definition in the output
- you can also define the custom media queries from JS and put the same values in a script so you can reuse them client side. Using the [appendExtensions](https://github.com/postcss/postcss-custom-media#appendextensions) might helps.

Is this enough for you ?

**Comment by jonathantneal** [comment]
It is now possible to import and export custom media to and from JS, JSON, and CSS, allowing you to use these queries with another library that could do this functionality for you. 🎉 

Checkout `importFrom` and `exportTo`.

https://github.com/postcss/postcss-custom-media#importfrom
https://github.com/postcss/postcss-custom-media#exportto
