### ISSUE TITLE
Using multiple selectors for a single block declaration block

### ISSUE THREAD

**Issue by brandondurham** [postcss/postcss-custom-media#15]
I’d love to be able to do this:

```css
@media (--small-viewport),
@media (--large-viewport) { … }
```

… but it doesn't seem to work. Is there a trick to using multiples with a single declaration?

**Comment by MoOx** [comment]
`@media (--small-viewport), (--large-viewport) { … }` ?

**Comment by brandondurham** [comment]
Fantastic. Thank you.
