### ISSUE TITLE
Better explanation

### ISSUE THREAD

**Issue by pixelass** [postcss/postcss-custom-media#20]
Can you please write the following section so others can understand it or better yet provide an example.

> Allows you to pass an object to define the `<media-query-list>` for each `<extension-name>`. These definitions will override any that exist in the CSS.

**Comment by MoOx** [comment]
```
extensions:{
  "--small-viewport": "max-width: 30em",
}
```

**Comment by pixelass** [comment]
not sure why this is closed without providing the requested documentation.

I had to look inside the test folder to figure out how it works.  
Don't worry though, I'll fork and send you a PR, then you can decide if you want to merge it.

Thx for the quick response though.

**Comment by kbytin** [comment]
+1 for adding this example to docs
