### ISSUE TITLE
Is this a part of future CSS standard?

### ISSUE THREAD

**Issue by slavafomin** [postcss/postcss-custom-media#21]
Hello!

Thank you for this great module!

It is a part of CSSNext suite and therefore should implement some future standard for CSS. However, I wasn't being able to find the specification for this "custom-media" standard.

Could you elaborate please? Thank you!

**Comment by slavafomin** [comment]
There is no mentions in the current draft about custom media queries:
https://drafts.csswg.org/mediaqueries/

Was it removed?

**Comment by MoOx** [comment]
This has been deffered to level 5, so not removed, just delayed https://github.com/w3c/csswg-drafts/blob/3abb7e30e5a7ec5f7504f5bc6470cf3c9a123b37/mediaqueries/deferred-for-level-5.txt

**Comment by slavafomin** [comment]
Well, I see. Thank you for clarification!
I would suggest to add this link to the README for future reference.
