### ISSUE TITLE
Incorrect expansion of @custom-media within import '...' $media-query

### ISSUE THREAD

**Issue by nwmcsween** [postcss/postcss-custom-media#28]
Given:
```
@import 'break-screen.css' screen;
@import 'break-print.css' print;
@import 'print' (--foo) print;
@import 'uses-unified-break.css';
```

Which with postcss-import results (I think):
```
@media screen {
  @custom-media --foo;
}
@media print {
  @custom-media --foo;
}
```
I would expect postcss-custom-media to apply `@media` rules correctly, such as
```
@media (--foo-from-print.css) print {
 contents of print.css
}
```
But instead it uses the last value of @custom-media and in this case the `print.css` value.

**Comment by jonathantneal** [comment]
While this issue has been long ignored, I want to let you know that this was not possible. This plugin does not support assigning custom media within media queries, which is also not supported in the spec that this plugin follows.
