### ISSUE TITLE
min-width & max-width

### ISSUE THREAD

**Issue by elliottmangham** [postcss/postcss-custom-media#32]
Hello,

Is it possible to set a breakpoint between a min and max width? For example:
`@custom-media --phone-and-tablet (min-width: 480px and max-width: 768px);`

This is a common practice, but I do not see any documentation for **postcss-custom-media** with this technique. I tried the above, which didn't work.

Thanks in advance

**Comment by jonathantneal** [comment]
Hi @elliottmangham, you can use [Media Query Ranges](https://jonathantneal.github.io/css-db/#mediaqueries-mq-ranges).

```css
@custom-media --phone-and-tablet (480px <= width <= 768px);
```

If you aren’t already using a library like cssnext, you’ll need to add support for range queries with https://github.com/postcss/postcss-media-minmax

**Comment by elliottmangham** [comment]
@jonathantneal, this works a dream. Thank you!
