### ISSUE TITLE
How can I use custom media with design tokens?

### ISSUE THREAD

**Issue by mindthetic** [postcss/postcss-custom-media#35]
I've begun to separate key design choices from my CSS which is helping me better manage the design of my projects using a tool called [Theo](https://github.com/salesforce-ux/theo). It works by storing abstract design values in a yaml or json file and then exports those values into you're preferred format. In our case the format is most likely CSS custom properties (although could be sass variables).

I'm using both Theo and Postcss-custom-media but I'm not sure how I can get them to work together because Theo outputs CSS custom variables which I don't think work inside custom media queries.

What are your thoughts?

**Comment by jonathantneal** [comment]
I’d like to add the ability to add custom selectors and custom media via JavaScript.

**Comment by jonathantneal** [comment]
This has been added in v7! 🎉 

Checkout `importFrom` and `exportTo`.

https://github.com/postcss/postcss-custom-media#importfrom
https://github.com/postcss/postcss-custom-media#exportto
