### ISSUE TITLE
Please add the option for disable all warnings

### ISSUE THREAD

**Issue by docccdev** [postcss/postcss-custom-media#36]
We use the common styles in different projects and do not always need media settings, I would like to turn off warnings for a clean console for example from postcss-custom-properties https://github.com/postcss/postcss-custom-properties#warnings

Thank you!

**Comment by docccdev** [comment]
Should I wait for changes?

**Comment by jonathantneal** [comment]
Done in v7 😄

**Comment by docccdev** [comment]
Thank you very much :) I'm waiting for the update version in postcss-preset-yenv :)
