### ISSUE TITLE
7.0 - media types not working

### ISSUE THREAD

**Issue by gpoitch** [postcss/postcss-custom-media#40]
Since 7.0, this no longer works:
`@custom-media --tabletUp screen and (min-width: 600px);`
The output is:
`@media screen(min-width: 600px)`
Seems to be missing 'and'

This works fine:
`@custom-media --tabletUp (min-width: 600px);`

**Comment by gpoitch** [comment]
Looks like maybe an issue with the 'and' regular expression.  Failing test: https://github.com/postcss/postcss-custom-media/commit/c8186a9f8a7ab94e7f5ec962aa816b7b93dc16cf

**Comment by jonathantneal** [comment]
Thanks for finding this. It has been fixed in 7.0.4, which (to whom it concerns) has been pushed into postcss-preset-env 6.0.6.
