### ISSUE TITLE
Broken AND operator since 7.x.x

### ISSUE THREAD

**Issue by redaxmedia** [postcss/postcss-custom-media#44]
Hey,

I experienced broken `AND` operator - issue occurred using version `7.0.2`:
```
@media (--media-small-min) and (--media-medium-max)
```

I did not test `OR` listings and `NOT` but these operators might be broken as well.

Had to downgraded to 6.0.0 to get my project back working. Please restore this feature as I don't want to create countless `AND` variations from my breakpoints... :-)

Great plugin!

**Comment by jonathantneal** [comment]
There is an incomplete PR to resolve this issue at https://github.com/postcss/postcss-custom-media/pull/46

The story can be worked on by anyone (with a failing test provided) at https://github.com/postcss/postcss-custom-media/tree/release/7.0.6

**Comment by redaxmedia** [comment]
Thank you very much for taking on the work... I will try my project with 7.0.6 once it has been released

**Comment by jonathantneal** [comment]
Thanks again for reporting this. Would you please retest in 7.0.6?

To whoever else sees this; this fix has been published to PostCSS Custom Media v7.0.6 and PostCSS Preset Env v6.1.1.

**Comment by redaxmedia** [comment]
Thank you, it looks like you fixed it :-)
