### ISSUE TITLE
Version 7.0.5 not being published to npm

### ISSUE THREAD

**Issue by emmenko** [postcss/postcss-custom-media#45]
Hey, somehow the latest version `7.0.5` does not seem to be published to npm

https://www.npmjs.com/package/postcss-custom-media

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/1110551/46789428-ac76d180-cd3c-11e8-822e-505b15787c2c.png">

Can you have a look and publish the version? Thanks 🙏

**Comment by jonathantneal** [comment]
Thanks, @emmenko. 7.0.5 has been published.
