### ISSUE TITLE
7.0.6 broke my css

### ISSUE THREAD

**Issue by andreymal** [postcss/postcss-custom-media#48]
```css
@custom-media --mobile-landscape (min-width: 568px) and (max-width: 767px);

.foo {
  @media (--mobile-landscape) {
    /* something */
  }
}
```

postcss-custom-media **7.0.5**

```css
@media (min-width: 568px) and (max-width: 767px) {
  .foo {
    /* something */
  }
}
```
postcss-custom-media **7.0.6**

```css
@media (min-width: 568px)(max-width: 767px) {
  .foo {
    /* something */
  }
}
```

**Comment by jonathantneal** [comment]
I am super sorry about that. While fixing another bug, I introduced this in 7.0.6. I’ve added more tests specifically for this situation that would protect against this happening again. Sorry for the delay in responding — it’s been very busy at work.

I hope you enjoy the new fix that is in 7.0.7. I’ve just published it! 🎉 

It’s also been updated in PostCSS Preset Env 6.1.2.
