### ISSUE TITLE
Breakpoints not working properly

### ISSUE THREAD

**Issue by ahahn95** [postcss/postcss-custom-media#50]
I'm using the code from the example

```
.hi {
    display: none;
}

@custom-media --small-viewport (max-width: 30em);

@media (--small-viewport) {
    .hi {
        display: block;
    }
}
```

to try to make a div appear on a Create-React-App project and it is not working. Is there something that I'm missing here?

**Comment by pascalduez** [comment]
Hi @ahahn95,

with your current code sample this `.hi` element will **always** be hidden.   
If you want it to be visible from `30em` uses `(min-width: 30em)`.

**Comment by ahahn95** [comment]
Ahh thank you. I also noticed that CRA uses PostCSS-Preset-Env which requires a dependency of  PostCSS-Custom-Media...but it is only included in stage 1 (and not stage 3, which is used by default)...looks like I need to make a PostCSS config file or eject etc.
