### ISSUE TITLE
Use PostCSS 8 events

### ISSUE THREAD

**Issue by ai** [postcss/postcss-custom-media#63]
Using the `Once` event is not a good practice. `postcss-custom-media` will not see changes made by other plugins (for instance, by `postcss-mixins`).

Moving to the `AtRule` event will improve other plugins' support.

**Comment by alexgagnon** [comment]
I put in a PR for this here: https://github.com/postcss/postcss-custom-media/pull/66

**Comment by dmgawel** [comment]
@jonathantneal looks like #66 is already merged. Would it be possible to mark a new release containing that change to resolve this issue?

**Comment by blvdmitry** [comment]
After updating to postcss 8, postcss-custom-media stopped working together with postcss-each and I assume it could be related to this issue. 
@jonathantneal Since a solution for it has been already merged – is there a chance we can have a patch release with it?

**Comment by sevilyilmaz** [comment]
@ai would it be possible to have a new version released by another member of PostCSS instead of being blocked by one?

**Comment by ai** [comment]
@sevilyilmaz I can try to release if we have PR

**Comment by IgorLesnevskiy** [comment]
@ai as far as I can see, this feature was merged a long time ago. I created merge request #76. I'm not familiar with the postcss release flow, but I guess you can merge it, create a tag and publish the package?

**Comment by spacedawwwg** [comment]
Is the package getting a bump?
